"""
BayesNetwork.py
An implementation of a Bayesian Network for Programming Assignment Four.
"""

import pandas as pd
import json

__author__ = "Chris Campell"
__version__ = "10/28/2017"


def enumeration_ask(X,e,bn):
    """
    enumeration_ask: Returns a probability distribution over X.
    :param X: The query variable for which probabilities are to be inferred.
    :param e: The observed values for variables E.
    :param bn: A Bayesian Network with variables {X} union E union Y (hidden variables).
    :return norm_dist_x: A normalized probability distribution over the query variable X.
    """
    return NotImplementedError


def enumerate_all(vars, e):
    """
    enumerate_all: Helper method for enumeration_ask, computes the joint probability distribution of the provided
        variables, given a set of observations.
    :param vars: A list of input variables for which to construct the joint from.
    :param e: A list of observations of the input variables which influence the joint distribution.
    :return joint_dist: The joint distribution of the provided 'vars' with the supplied observations 'e'.
    """
    return NotImplementedError


def construct_probability_table(node, observations, dependencies=None, prob_tables_dependencies=None):
    """
    construct_probability_table: Builds a probability table for the provided node given the provided observations-
        (the number of Trues and False's).
    :param node: A node in the Bayesian Network.
    :param observations: The observations of the evidence variables in the network.
    :param dependencies: The nodes that the provided node is dependent on (if any).
    :param prob_tables_dependencies: A dictionary of probability tables for each of the dependencies listed in
        dependencies. These tables are necessary to calculate the probability of a conditionally dependent node.
    :return node_prob_table: A probability table for the supplied node generated by the observations of the
        dependent variables.
    """
    node_prob_table = {}
    if dependencies is not None:
        # The node is independent; simply sum the number of true and false's:
        # node_observations = observations.groupby(node).count()
        # node_value_counts = observations[node].value_counts()
        num_true = observations[node].value_counts()[True]
        total_num_obs = len(observations[node])
        node_prob_table[True] = (num_true / total_num_obs)
        node_prob_table[False] = 1 - node_prob_table[True]
    else:
        # The node is dependent on the nodes in the dependencies list:
        #       P(Node | Dependency[0], Dependency[1], ..., Dependency[n]):
        for dependency in dependencies:
            return NotImplementedError
    return node_prob_table


def main(bayes_net, observations):
    prob_tables = {}
    for node in bayes_net:
        is_independent = True
        dependencies = []
        # for child in bayes_net[node]:
        # Is the current node a child of another node, or is it independent?
        for parent, child_list in bayes_net.items():
            if node in child_list:
                # The node is a child of another node, it is dependent.
                is_independent = False
                # The node is dependent upon it's parent:
                dependencies.append(parent)
                break
            else:
                # The node is not a child of another node, it is independent.
                pass
        if node not in prob_tables:
            # The node does not have a probability table constructed yet:
            if is_independent:
                '''
                If it is an independent node, just build the probability table given the observations of the evidence
                    variables:
                '''
                prob_tables[node] = construct_probability_table(node=node, observations=observations)
            else:
                # The node is conditionally dependent, build the probability table given the probability tables of the
                #   dependent nodes.
                for dependency in dependencies:
                    if dependency not in prob_tables:
                        # The dependent node has no previously constructed probability table:
                        # TODO: Uh-oh, this function needs to be recursive. What if the dependent is dependent?
                        pass
            prob_tables[node] = construct_probability_table(
                node=node, dependencies=dependencies, observations=observations)
        pass

if __name__ == '__main__':
    bn_one_path = 'bn1.json'
    observations_one_path = 'data1.csv'
    bn_two_path = 'bn2.json'
    observations_two_path = 'data2.csv'
    with open(bn_one_path, 'r') as fp:
        bayes_net_one = json.load(fp=fp)
    with open(bn_two_path, 'r') as fp:
        bayes_net_two = json.load(fp=fp)
    with open(observations_one_path, 'r') as fp:
        observations_one = pd.read_csv(fp)
    with open(observations_two_path, 'r') as fp:
        observations_two = pd.read_csv(fp)
    main(bayes_net=bayes_net_one, observations=observations_one)
